export const START_CALENDARS_REQUEST = "START_CALENDAR_REQUEST";
export const HANDEL_CALENDARS_REQUEST = "HANDLE_CALENDARS_REQUEST";
export const HANDLE_CALENDARS_REQUEST_ERROR = "HANDLE_CALENDARS_REQUEST_ERROR";

export const GET_USER_DATA = "GET_USER_DATA";
export const START_REFRESH_USER_DATA_REQUEST = "START_REFRESH_USER_DATA_REQUEST";
export const HANDLE_REFRESH_USER_DATA_REQUEST = "HANDLE_REFRESH_USER_DATA_REQUEST";
export const HANDLE_REFRESH_USER_DATA_REQUEST_ERROR = "HANDLE_REFRESH_USER_DATA_REQUEST_ERROR";


export const SET_VIEW_CALENDAR_ID = "SET_VIEW_CALENDAR_ID";
export const START_FETCH_VIEW_CALENDAR = "START_FETCH_VIEW_CALENDAR";
export const RESET_VIEW_CALENDAR = "RESET_VIEW_CALENDAR";
export const LOAD_VIEW_CALENDAR_CONTENT = "LOAD_VIEW_CALENDAR_CONTENT";
export const HANDLE_LOADING_VIEW_CALENDAR_ERROR = "HANDLE_LOADING_VIEW_CALENDAR_ERROR";
export const MARK_LOADING_VIEW_CALENDAR_AS_DONE = "MARK_LOADING_VIEW_CALENDAR_AS_DONE"


export const START_PLANNER_REQUEST = "START_PLANNER_REQUEST";
export const HANDLE_PLANNER_REQUEST = "HANDLE_PLANNER_REQUEST";
export const HANDLE_PLANNER_REQUEST_ERROR = "HANDLE_PLANNER_REQUEST_ERROR";
