export const START_CALENDARS_REQUEST = "START_CALENDAR_REQUEST";

export const HANDLE_CALENDARS_REQUEST = "HANDLE_CALENDARS_REQUEST";

export const HANDLE_CALENDARS_ERROR = "HANDLE_CALENDARS_ERROR";

export const ADD_SINGLE_CALENDAR = "ADD_SINGLE_CALENDAR";

export const VIEW_SINGLE_CALENDAR = "VIEW_SINGLE_CALENDAR";

export const UPDATE_SINGLE_CALENDAR = "UPDATE_SINGLE_CALENDAR";

export const DELETE_SINGLE_CALENDAR = "DELETE_SINGLE_CALENDAR";
